"""Create a repository to reference the protoc toolchain.
"""

def _toolchain_repo_impl(repository_ctx):
    build_content = """# Generated by proto/private/protoc/protoc_toolchains.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the rules_proto_toolchains macro
# so you don't normally need to interact with these targets.
"""

    build_content += """
load("@rules_proto//proto/private/rules:proto_toolchain_rule.bzl", "proto_toolchain")
proto_toolchain(
    name = "toolchain",
    proto_compiler = "@com_google_protobuf//:protoc",
    visibility = ["//visibility:public"],
)
toolchain(
    name = "toolchain_toolchain",
    # Bazel does not follow this attribute during analysis, so the referenced repo
    # will only be fetched if this toolchain is selected.
    toolchain = "//:toolchain",
    toolchain_type = "@rules_proto//proto:toolchain_type",
)
"""
    repository_ctx.file("BUILD.bazel", build_content)

protoc_toolchain_repo = repository_rule(
    _toolchain_repo_impl,
    doc = """\
    Creates a single repository with a toolchain definition
    that can be registered or selected.
    """,
)
